const bookings = JSON.parse(localStorage.getItem('kisanSetuAdminBookings') || 'null') || [
  { id: 'K-1042', name: 'Suresh Jadhav', centre: 'Shivajinagar Centre', crop: 'Wheat', slot: '08:00 - 10:00', queue: 2, status: 'In progress', phone: '98XXXXXX21' },
  { id: 'H-0831', name: 'Meena Pawar', centre: 'Hadapsar Centre', crop: 'Rice', slot: '08:00 - 10:00', queue: 5, status: 'Waiting', phone: '97XXXXXX84' },
  { id: 'B-0557', name: 'Ramesh Shinde', centre: 'Baramati Centre', crop: 'Soybean', slot: '10:00 - 12:00', queue: 9, status: 'Waiting', phone: '91XXXXXX16' },
  { id: 'S-1028', name: 'Kavita More', centre: 'Shivajinagar Centre', crop: 'Maize', slot: '08:00 - 10:00', queue: 0, status: 'Completed', phone: '88XXXXXX43' },
  { id: 'H-0794', name: 'Vilas Gaikwad', centre: 'Hadapsar Centre', crop: 'Wheat', slot: '10:00 - 12:00', queue: 12, status: 'Waiting', phone: '86XXXXXX72' },
  { id: 'B-0491', name: 'Sunita Kale', centre: 'Baramati Centre', crop: 'Rice', slot: '10:00 - 12:00', queue: 1, status: 'In progress', phone: '95XXXXXX30' }
];
const centres = JSON.parse(localStorage.getItem('kisanSetuAdminCentres') || 'null') || [
  { name: 'Shivajinagar Centre', location: 'Pune North', queue: 18, capacity: 72, windows: 4, status: true },
  { name: 'Hadapsar Centre', location: 'Pune East', queue: 11, capacity: 48, windows: 3, status: true },
  { name: 'Baramati Centre', location: 'Pune South', queue: 25, capacity: 86, windows: 5, status: true }
];
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const save = () => localStorage.setItem('kisanSetuAdminBookings', JSON.stringify(bookings));
function initials(name) { return name.split(' ').map((word) => word[0]).slice(0, 2).join(''); }
function toast(message) { const element = $('#toast'); element.textContent = message; element.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => element.classList.remove('show'), 2600); }
function statusClass(status) { return status === 'In progress' ? 'progress' : status.toLowerCase(); }
function bookingRow(booking) { return `<tr><td><div class="farmer-cell"><span class="mini-avatar">${initials(booking.name)}</span><div><strong>${booking.name}</strong><small>${booking.id}</small></div></div></td><td>${booking.centre}</td><td>${booking.crop}</td><td>${booking.slot}</td><td>${booking.queue === 0 ? 'Ready' : `${booking.queue} ahead`}</td><td><span class="status-pill ${statusClass(booking.status)}">${booking.status}</span></td><td><button class="row-action" data-detail="${booking.id}" aria-label="View ${booking.name} details">⋯</button></td></tr>`; }
function renderBookings(target = '#bookingTable', list = bookings.slice(0, 5)) { $(target).innerHTML = list.map(bookingRow).join('') || '<tr><td colspan="7">No bookings match your filters.</td></tr>'; $$(`${target} [data-detail]`).forEach((button) => button.addEventListener('click', () => showDetails(button.dataset.detail))); }
function renderActivity() { $('#activityList').innerHTML = `<div class="activity-item"><span class="activity-icon">✓</span><div><strong>Token S-1028 completed</strong><small>Shivajinagar Centre · 4 min ago</small></div></div><div class="activity-item"><span class="activity-icon">!</span><div><strong>Queue is building at Baramati</strong><small>25 farmers waiting · 11 min ago</small></div></div><div class="activity-item"><span class="activity-icon">↗</span><div><strong>New booking received</strong><small>Meena Pawar · 18 min ago</small></div></div>`; }
function renderCentres() { $('#centreAdminGrid').innerHTML = centres.map((centre, index) => `<article class="centre-admin-card"><header><div><p class="eyebrow">${centre.location}</p><h3>${centre.name}</h3></div><span class="status-pill ${centre.status ? 'completed' : 'waiting'}">${centre.status ? 'Open' : 'Paused'}</span></header><p class="muted">${centre.queue} farmers currently waiting</p><div class="capacity"><b style="width:${centre.capacity}%"></b></div><div class="centre-details"><div><strong>${centre.queue}</strong><small>In queue</small></div><div><strong>${centre.capacity}%</strong><small>Capacity</small></div><div><strong>${centre.windows}</strong><small>Windows</small></div></div><div class="toggle-row"><span>Accept new bookings</span><button class="switch ${centre.status ? 'on' : ''}" data-centre-toggle="${index}" aria-label="Toggle bookings"><b></b></button></div></article>`).join(''); $('#activeCentres').textContent = `${centres.filter((centre) => centre.status).length} / ${centres.length}`; $$('[data-centre-toggle]').forEach((button) => button.addEventListener('click', () => { const centre = centres[button.dataset.centreToggle]; centre.status = !centre.status; localStorage.setItem('kisanSetuAdminCentres', JSON.stringify(centres)); renderCentres(); toast(`${centre.name} is now ${centre.status ? 'accepting' : 'not accepting'} new bookings.`); })); }
function showDetails(id) { const booking = bookings.find((item) => item.id === id); if (!booking) return; $('#detailTitle').textContent = booking.name; $('#detailContent').innerHTML = `<div class="detail-grid"><div class="detail-box"><small>Digital token</small><strong>${booking.id}</strong></div><div class="detail-box"><small>Contact</small><strong>${booking.phone}</strong></div><div class="detail-box"><small>Centre</small><strong>${booking.centre}</strong></div><div class="detail-box"><small>Crop</small><strong>${booking.crop}</strong></div><div class="detail-box"><small>Time slot</small><strong>${booking.slot}</strong></div><div class="detail-box"><small>Queue position</small><strong>${booking.queue === 0 ? 'Ready' : `${booking.queue} ahead`}</strong></div></div><label>Status<select id="detailStatus"><option ${booking.status === 'Waiting' ? 'selected' : ''}>Waiting</option><option ${booking.status === 'In progress' ? 'selected' : ''}>In progress</option><option ${booking.status === 'Completed' ? 'selected' : ''}>Completed</option></select></label><button class="primary-button full" id="saveStatus">Save status</button>`; $('#detailModal').classList.add('open'); $('#detailModal').setAttribute('aria-hidden', 'false'); $('#saveStatus').addEventListener('click', () => { booking.status = $('#detailStatus').value; save(); renderBookings(); renderBookings('#allBookingTable', filteredBookings()); closeModal('detailModal'); toast(`Status updated for ${booking.name}.`); }); }
function filteredBookings() { const search = ($('#searchInput')?.value || '').toLowerCase(); const status = $('#statusFilter')?.value || 'all'; const centre = $('#centreFilter')?.value || 'all'; return bookings.filter((booking) => { const searchable = `${booking.name} ${booking.id} ${booking.centre}`.toLowerCase(); return searchable.includes(search) && (status === 'all' || booking.status === status) && (centre === 'all' || booking.centre === centre); }); }
function showView(view) { const names = { overview: ['OVERVIEW', 'Procurement operations'], bookings: ['BOOKINGS', 'All procurement bookings'], centres: ['CENTRES', 'Centre performance'], reports: ['REPORTS', 'Procurement performance'] }; $$('.page-content').forEach((section) => section.classList.add('hidden')); $(`#${view}View`).classList.remove('hidden'); $('#viewName').textContent = names[view][0]; $('#pageTitle').textContent = names[view][1]; $$('.nav-link').forEach((button) => button.classList.toggle('active', button.dataset.view === view)); if (view === 'bookings') renderBookings('#allBookingTable', filteredBookings()); if (view === 'centres') renderCentres(); }
function closeModal(id) { $(`#${id}`).classList.remove('open'); $(`#${id}`).setAttribute('aria-hidden', 'true'); }
function openAddBooking() { $('#addModal').classList.add('open'); $('#addModal').setAttribute('aria-hidden', 'false'); }
function exportCsv() { const rows = [['Token','Farmer','Centre','Crop','Slot','Queue','Status'], ...bookings.map((booking) => [booking.id, booking.name, booking.centre, booking.crop, booking.slot, booking.queue, booking.status])]; const csv = rows.map((row) => row.join(',')).join('\n'); const link = document.createElement('a'); link.href = `data:text/csv;charset=utf-8,${encodeURIComponent(csv)}`; link.download = 'kisansetu-bookings.csv'; link.click(); toast('CSV report downloaded.'); }
$$('.nav-link').forEach((button) => button.addEventListener('click', () => showView(button.dataset.view)));
$$('[data-view-target]').forEach((button) => button.addEventListener('click', () => showView(button.dataset.viewTarget)));
$('#menuToggle').addEventListener('click', () => $('#sidebar').classList.toggle('open'));
$('#refreshBtn').addEventListener('click', () => { renderBookings(); renderActivity(); toast('Dashboard data refreshed.'); });
$('#exportBtn').addEventListener('click', exportCsv); $('#exportAllBtn').addEventListener('click', exportCsv); $('#downloadReportBtn').addEventListener('click', exportCsv);
$('#addBookingBtn').addEventListener('click', openAddBooking); $('#addBookingBtnTwo').addEventListener('click', openAddBooking);
$('#viewAlertsBtn').addEventListener('click', () => toast('All activity alerts are shown on the overview.'));
$('#notificationBtn').addEventListener('click', () => toast('2 updates need your attention.'));
$('#settingsBtn').addEventListener('click', () => toast('Settings are available to district coordinators.'));
$('#broadcastBtn').addEventListener('click', () => toast('Broadcast composer is ready for centre updates.'));
$('#searchInput').addEventListener('input', () => renderBookings('#allBookingTable', filteredBookings())); $('#statusFilter').addEventListener('change', () => renderBookings('#allBookingTable', filteredBookings())); $('#centreFilter').addEventListener('change', () => renderBookings('#allBookingTable', filteredBookings()));
$('#addForm').addEventListener('submit', (event) => { event.preventDefault(); const centre = $('#addCentre').value; const prefix = centre[0]; bookings.unshift({ id: `${prefix}-${Math.floor(1000 + Math.random() * 8999)}`, name: $('#addName').value, centre, crop: $('#addCrop').value, slot: $('#addSlot').value, queue: 1, status: 'Waiting', phone: 'Not provided' }); save(); renderBookings(); renderBookings('#allBookingTable', filteredBookings()); closeModal('addModal'); $('#addForm').reset(); toast('New booking added to the queue.'); });
$$('[data-close]').forEach((button) => button.addEventListener('click', () => closeModal(button.dataset.close))); $$('.modal').forEach((modal) => modal.addEventListener('click', (event) => { if (event.target === modal) closeModal(modal.id); }));
document.addEventListener('keydown', (event) => { if (event.key === 'Escape') $$('.modal.open').forEach((modal) => closeModal(modal.id)); });
renderBookings(); renderActivity();
